(function(){
  function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function checks(labels,selected){return labels.map((label,index)=>`<span class="check">${selected===(['ok','ng','ask'][index])?'☑':'□'} ${label}</span>`).join('　');}
  function descriptionMarkup(value){return esc(String(value??'').replace(/\r\n?/g,'\n'));}
  function featureMarkup(value){const tags=String(value??'').split('/').map(tag=>tag.trim()).filter(Boolean).slice(0,3);if(!tags.length)return '';return `<div class="sheet-features" aria-label="キーボードの特徴"><div class="feature-tags">${tags.map(tag=>`<span class="feature-tag">${esc(tag)}</span>`).join('')}</div></div>`;}
  function imagesMarkup(images){return SheetImages.normalize(images).map(image=>`<img class="sheet-user-image" src="${esc(image.src)}" alt="${esc(image.name)}" style="left:${image.x}%;top:${image.y}%;width:${image.width}%">`).join('');}
  function markup(sheet,template,blank=false,showEventLogo=true){const value=v=>blank?'':(v||'');return `${SheetBands.markup(sheet.bandStyle)}<div class="sheet-top">${showEventLogo?'<img class="nagare-logo" src="assets/nagare-key/logo.png" alt="ながれキー"><img class="ttt-logo" src="assets/Touch-Type-Talkey/ttt_logo.png" alt="Touch,Type&amp;Talkey"><span class="tenkey-mark">#天キーVol.12</span>':''}<h2 class="sheet-name">${esc(value(sheet.keyboardName))}</h2><div class="sheet-exhibitor"><span class="exhibitor-label">OWNER</span><span class="exhibitor-value">${esc(value(sheet.exhibitor))}</span></div></div><div class="sheet-meta"><div class="meta-item"><span class="meta-label">KEY SWITCH</span><span class="meta-value">${esc(value(sheet.switchName))}</span></div><div class="meta-item"><span class="meta-label">KEYCAPS</span><span class="meta-value">${esc(value(sheet.keycaps))}</span></div></div>${featureMarkup(value(sheet.feature))}<div class="sheet-description">${descriptionMarkup(value(sheet.description),template)}</div><div class="permission-grid"><div><span class="permission-label">試し打ち</span><span class="permission">${checks(['OK','NG','声かけて'],sheet.typing)}</span></div><div><span class="permission-label">撮影・SNS投稿</span><span class="permission">${checks(['OK','NG'],sheet.photo)}</span></div></div><div class="sheet-footer"></div>${blank?'':imagesMarkup(sheet.images)}`;}
  function fitDescription(card){const element=card.querySelector('.sheet-description');if(!element)return 'normal';const levels=['normal','small','smaller','minimum'];element.classList.remove(...levels);let chosen='minimum';for(const level of levels){element.classList.add(level);if(element.scrollHeight<=element.clientHeight+1){chosen=level;break;}}element.classList.add(chosen);return chosen;}
  function lineCount(element){const range=document.createRange();range.selectNodeContents(element);return Array.from(range.getClientRects()).filter(rect=>rect.width>0&&rect.height>0).length;}
  function fitKeyboardName(card,singleLine=false){const element=card.querySelector('.sheet-name');if(!element)return 'name-normal';const levels=['name-normal','name-small','name-smaller','name-minimum'];element.classList.remove(...levels);element.classList.toggle('name-single-line',singleLine);let chosen='name-normal';for(let index=0;index<levels.length;index++){element.classList.add(levels[index]);const lines=lineCount(element);const fits=singleLine?element.scrollWidth<=element.clientWidth+1:(index===0?lines<=1:lines<=2);if(fits){chosen=levels[index];break;}chosen=levels[index];}element.classList.add(chosen);return chosen;}
  window.SheetCard={markup,fitDescription,fitKeyboardName};
})();
